
---

######################################################################################################

- name: Remove /data/system/ contents
  file:
    path: /var/lib/cassandra/data/system/*
    state: absent

######################################################################################################

- name: Update /etc/init.d/cassandra
  lineinfile:
    dest: /etc/init.d/cassandra
    regexp: '^#*CMD_PATT='
    line: 'CMD_PATT="cassandra"'

######################################################################################################

- name: Copy over cassandra.yaml template
  template:
    dest: /etc/cassandra/cassandra.yml
    src: cassandra.yaml.j2

######################################################################################################

- name: Update /etc/cassandra/cassandra-rackdc.properties
  lineinfile:
    dest: /etc/cassandra/cassandra-rackdc.properties
    regexp: '^#*dc=.*'
    line: "{{ rackdc_properties }}"

######################################################################################################

- name: Reboot Machine
  shell: reboot

######################################################################################################

- name: Ensure Cassandra is running and enabled on boot.
  service: name=cassandra state=started enabled=yes
